"""initial

Revision ID: e90343e66880
Revises: 
Create Date: 2026-03-02 14:28:49.444076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e90343e66880'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('table_name', sa.String(length=50), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('old_values', sa.Text(), nullable=True),
    sa.Column('new_values', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_table_record', ['table_name', 'record_id'], unique=False)
        batch_op.create_index('ix_audit_time', ['created_at'], unique=False)
        batch_op.create_index('ix_audit_user', ['user_id'], unique=False)

    op.create_table('containers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('container_number', sa.String(length=20), nullable=True),
    sa.Column('container_type', sa.String(length=10), nullable=True),
    sa.Column('booking_number', sa.String(length=50), nullable=True),
    sa.Column('carrier', sa.String(length=100), nullable=True),
    sa.Column('forwarder', sa.String(length=100), nullable=True),
    sa.Column('pol', sa.String(length=100), nullable=True),
    sa.Column('pod', sa.String(length=100), nullable=True),
    sa.Column('etd', sa.Date(), nullable=True),
    sa.Column('eta', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'LOADING', 'CLOSED', 'SHIPPED', 'ARRIVED', 'UNLOADED', name='containerstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('containers', schema=None) as batch_op:
        batch_op.create_index('ix_container_status', ['status'], unique=False)
        batch_op.create_index('ix_container_warehouse', ['warehouse_id'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('warehouse_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('wr_number', sa.String(length=30), nullable=False),
    sa.Column('date_received', sa.Date(), nullable=False),
    sa.Column('commodity', sa.String(length=300), nullable=False),
    sa.Column('qty_total', sa.Integer(), nullable=False),
    sa.Column('qty_unit_type', sa.Enum('CAJAS', 'UNIDADES', 'PALETAS', name='qtyunittype'), nullable=False),
    sa.Column('cbm_total', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('kg_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('RECEIVED', 'PARTIALLY_LOADED', 'LOADED', 'HOLD', 'CANCELLED', name='wrstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wr_number')
    )
    with op.batch_alter_table('warehouse_receipts', schema=None) as batch_op:
        batch_op.create_index('ix_wr_customer', ['customer_id'], unique=False)
        batch_op.create_index('ix_wr_date', ['date_received'], unique=False)
        batch_op.create_index('ix_wr_warehouse_status', ['warehouse_id', 'status'], unique=False)

    op.create_table('container_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('container_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('LOADING', 'CLOSED', 'SHIPPED', 'ARRIVED', 'UNLOADED', name='eventtype'), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('container_events', schema=None) as batch_op:
        batch_op.create_index('ix_event_container', ['container_id'], unique=False)

    op.create_table('container_load_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('container_id', sa.Integer(), nullable=False),
    sa.Column('wr_id', sa.Integer(), nullable=False),
    sa.Column('qty_loaded', sa.Integer(), nullable=False),
    sa.Column('cbm_loaded', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('kg_loaded', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('loaded_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('cbm_loaded >= 0', name='ck_cbm_nonneg'),
    sa.CheckConstraint('kg_loaded >= 0', name='ck_kg_nonneg'),
    sa.CheckConstraint('qty_loaded > 0', name='ck_qty_positive'),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.ForeignKeyConstraint(['wr_id'], ['warehouse_receipts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('container_id', 'wr_id', name='uq_container_wr')
    )
    with op.batch_alter_table('container_load_lines', schema=None) as batch_op:
        batch_op.create_index('ix_loadline_wr', ['wr_id'], unique=False)

    op.create_table('container_tracking_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('container_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('event_description', sa.String(length=300), nullable=True),
    sa.Column('location_name', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('container_tracking_points', schema=None) as batch_op:
        batch_op.create_index('ix_tracking_container_ts', ['container_id', 'timestamp'], unique=False)

    op.create_table('freight_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('container_id', sa.Integer(), nullable=False),
    sa.Column('supplier', sa.String(length=200), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'PARTIAL', 'PAID', 'CANCELLED', name='invoicestatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_no', name='uq_invoice_no')
    )
    with op.batch_alter_table('freight_invoices', schema=None) as batch_op:
        batch_op.create_index('ix_freight_container', ['container_id'], unique=False)

    op.create_table('freight_proration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('container_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('cbm_share', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('kg_share', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('container_id', 'customer_id', name='uq_proration_container_customer')
    )
    op.create_table('freight_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('freight_invoice_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('amount > 0', name='ck_payment_positive'),
    sa.ForeignKeyConstraint(['freight_invoice_id'], ['freight_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('freight_payments')
    op.drop_table('freight_proration')
    with op.batch_alter_table('freight_invoices', schema=None) as batch_op:
        batch_op.drop_index('ix_freight_container')

    op.drop_table('freight_invoices')
    with op.batch_alter_table('container_tracking_points', schema=None) as batch_op:
        batch_op.drop_index('ix_tracking_container_ts')

    op.drop_table('container_tracking_points')
    with op.batch_alter_table('container_load_lines', schema=None) as batch_op:
        batch_op.drop_index('ix_loadline_wr')

    op.drop_table('container_load_lines')
    with op.batch_alter_table('container_events', schema=None) as batch_op:
        batch_op.drop_index('ix_event_container')

    op.drop_table('container_events')
    with op.batch_alter_table('warehouse_receipts', schema=None) as batch_op:
        batch_op.drop_index('ix_wr_warehouse_status')
        batch_op.drop_index('ix_wr_date')
        batch_op.drop_index('ix_wr_customer')

    op.drop_table('warehouse_receipts')
    op.drop_table('user_roles')
    with op.batch_alter_table('containers', schema=None) as batch_op:
        batch_op.drop_index('ix_container_warehouse')
        batch_op.drop_index('ix_container_status')

    op.drop_table('containers')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_user')
        batch_op.drop_index('ix_audit_time')
        batch_op.drop_index('ix_audit_table_record')

    op.drop_table('audit_log')
    op.drop_table('warehouses')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('customers')
    # ### end Alembic commands ###
